### ISSUE TITLE
How is Motor Status flag #3 triggered?

### ISSUE THREAD

**Issue by clort81** [hurzhurz/tsdz2#2]
Is it a boolean 0/1 for "are spinning", or does it switch to one value and back, every time the pedals make a rotation?

If it triggers once per rotation, it could be used by controller to derive pedaling cadence, which is needed for display software to derive pedaling power (watts) from torque sensor data.

**Comment by hurzhurz** [comment]
It is the first one, just a spinning indicator and not usuable to get the cadence.
Though all the information is somewhat old now. I don't know if there were changes in newer motors.

In case you are interested: Casainho and me were able to modify the firmware to get more data: https://endless-sphere.com/forums/viewtopic.php?f=28&t=94351
Also Casainho did start to develop new firmware: https://opensourceebikefirmware.bitbucket.io/

**Comment by clort81** [comment]
Thanks, however the v2 Firmware project has stalled for a year and Casainho has informed me he's moved on to another motor.

I will look into minimalist additional hardware to get cadence and ampere draw from battery to my analysis device.  Closing.
